name: CI

on: 
  pull_request:
    branches:
      - master
  

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TFE_TOKEN: ${{secrets.TFE_TOKEN}}
      GH_ACCESS_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - uses: ./.github/workflows/lerna.yaml

