name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci


    - name: Install dependencies
      run: |
        mkdir -p ~/.terraform.d
        cat <<EOT >> ~/.terraform.d/credentials.tfrc.json
        {
          "credentials": {
            "app.terraform.io": {
              "token": "$TFE_TOKEN"
            }
          }
        }
        EOT
      env:
        TFE_TOKEN: ${{secrets.TFE_TOKEN}}

    - name: Deploy to production
      run: |
        npx lerna bootstrap
        npx lerna run get


    - name: Run Terraform CDK
      uses: hashicorp/terraform-cdk-action@v0.1.0
      with:
        terraformVersion: 1.3.0
        cdktfVersion: 0.12.2
        workingDirectory: packages/organization
        stackName: my-stack
        mode: plan-only
        terraformCloudToken: ${{ secrets.TFE_TOKEN }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
