name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci


    - name: Install dependencies
      run: |
        mkdir -p ~/.terraform.d
        cat <<EOT >> ~/.terraform.d/credentials.tfrc.json
        echo {
              "credentials": {
                "app.terraform.io": {
                  "token": "$TFE_TOKEN"
                }
              }
            }
        EOT
        cat ~/.terraform.d/credentials.tfrc.json
      env:
        TFE_TOKEN: ${{secrets.TFE_TOKEN}}

    - name: Deploy to production
      run: |
        npx lerna bootstrap
        npx lerna run get
        npx lerna run build
        npx lerna run plan

