name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install cdktf
      run: npm install --global cdktf-cli@latest


    - name: Install dependencies
      run: npm install

    - name: Deploy to production
      run: |
        npx lerna bootstrap
        npx lerna run get
        npx lerna run build
